using DataAccess.Core.Repositories;
using Microsoft.EntityFrameworkCore;
using CoreStudent = DataAccess.Core.Models.Student;
using ScaffoldedStudent = DataAccess.EfDbFirst.Scaffolded.Student;
using DataAccess.EfDbFirst.Scaffolded;

namespace DataAccess.EfDbFirst;

/// <summary>
/// Task 4.10 - fulfills the shared IRepository&lt;Core.Models.Student&gt;
/// seam by mapping to/from the REAL scaffolded Student shape (generated by
/// `dotnet ef dbcontext scaffold` against DataAccessWeek4). Aliased as
/// ScaffoldedStudent here purely to disambiguate it from the domain
/// CoreStudent — EF's scaffolder names classes after the table by
/// convention, so a "Students" table scaffolds to a class literally named
/// "Student", colliding with DataAccess.Core.Models.Student. This mapping
/// step is exactly what DB First always costs you: the scaffolded class
/// belongs to "another team"'s schema, so bridging it onto your own domain
/// model is explicit and visible here, rather than the domain model and
/// the table happening to be defined by the same code (as in Code First,
/// where there is no bridge to write).
/// </summary>
public class EfDbFirstStudentRepository : IRepository<CoreStudent>
{
    private readonly ScaffoldedDbContext _context;

    public EfDbFirstStudentRepository(ScaffoldedDbContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<CoreStudent>> GetAllAsync()
    {
        var rows = await _context.Students.AsNoTracking().ToListAsync();
        return rows.Select(ToStudent);
    }

    public async Task<CoreStudent?> GetByIdAsync(int id)
    {
        var row = await _context.Students.AsNoTracking().FirstOrDefaultAsync(s => s.Id == id);
        return row is null ? null : ToStudent(row);
    }

    public async Task<CoreStudent> AddAsync(CoreStudent entity)
    {
        var row = ToRow(entity);
        _context.Students.Add(row);
        await _context.SaveChangesAsync();
        entity.Id = row.Id;
        return entity;
    }

    public async Task<bool> UpdateAsync(int id, CoreStudent entity)
    {
        var existing = await _context.Students.FirstOrDefaultAsync(s => s.Id == id);
        if (existing is null) return false;

        existing.Name = entity.Name;
        existing.Age = entity.Age;
        existing.Email = entity.Email;
        existing.EnrolledOn = entity.EnrolledOn;

        await _context.SaveChangesAsync();
        return true;
    }

    public async Task<bool> DeleteAsync(int id)
    {
        var existing = await _context.Students.FirstOrDefaultAsync(s => s.Id == id);
        if (existing is null) return false;

        _context.Students.Remove(existing);
        await _context.SaveChangesAsync();
        return true;
    }

    private static CoreStudent ToStudent(ScaffoldedStudent row) => new()
    {
        Id = row.Id,
        Name = row.Name,
        Age = row.Age,
        Email = row.Email,
        EnrolledOn = row.EnrolledOn
    };

    private static ScaffoldedStudent ToRow(CoreStudent student) => new()
    {
        Id = student.Id,
        Name = student.Name,
        Age = student.Age,
        Email = student.Email,
        EnrolledOn = student.EnrolledOn
    };
}